/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as DocsRouteRouteImport } from './routes/docs/route'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedOrgSlugRouteRouteImport } from './routes/_authenticated/$orgSlug/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as ApiStatusRouteImport } from './routes/api/status'
import { Route as ConfigureIndexRouteImport } from './routes/configure/index'
import { Route as DevSplatRouteImport } from './routes/dev/$'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsSitemapDotxmlRouteImport } from './routes/docs/sitemap[.]xml'
import { Route as authenticationAuthPathRouteImport } from './routes/(authentication)/auth/$path'
import { Route as AuthenticatedOrgSlugIndexRouteImport } from './routes/_authenticated/$orgSlug/index'
import { Route as AuthenticatedOnboardingIndexRouteImport } from './routes/_authenticated/onboarding/index'
import { Route as AuthenticatedOrganizationsIndexRouteImport } from './routes/_authenticated/organizations/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiChatSplatRouteImport } from './routes/api/chat/$'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'
import { Route as DocsSectionIndexRouteImport } from './routes/docs/$section/index'
import { Route as DocsApiIndexRouteImport } from './routes/docs/api/index'
import { Route as AuthenticatedOrgSlugAgentsIndexRouteImport } from './routes/_authenticated/$orgSlug/agents/index'
import { Route as AuthenticatedOrgSlugApiKeysIndexRouteImport } from './routes/_authenticated/$orgSlug/api-keys/index'
import { Route as AuthenticatedOrgSlugMembersIndexRouteImport } from './routes/_authenticated/$orgSlug/members/index'
import { Route as AuthenticatedOrgSlugSandboxesIndexRouteImport } from './routes/_authenticated/$orgSlug/sandboxes/index'
import { Route as AuthenticatedOrgSlugSettingsIndexRouteImport } from './routes/_authenticated/$orgSlug/settings/index'
import { Route as AuthenticatedSettingsAccountIndexRouteImport } from './routes/_authenticated/settings/account/index'
import { Route as AuthenticatedSettingsSecurityIndexRouteImport } from './routes/_authenticated/settings/security/index'
import { Route as DocsSectionPageIndexRouteImport } from './routes/docs/$section/$page/index'
import { Route as AuthenticatedOrgSlugAgentsAgentIdIndexRouteImport } from './routes/_authenticated/$orgSlug/agents/$agentId/index'
import { Route as AuthenticatedOrgSlugAgentsNewIndexRouteImport } from './routes/_authenticated/$orgSlug/agents/new/index'
import { Route as AuthenticatedOrgSlugSandboxesSandboxProviderIdIndexRouteImport } from './routes/_authenticated/$orgSlug/sandboxes/$sandboxProviderId/index'
import { Route as AuthenticatedOrgSlugSandboxesNewIndexRouteImport } from './routes/_authenticated/$orgSlug/sandboxes/new/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRouteRoute = DocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrgSlugRouteRoute =
  AuthenticatedOrgSlugRouteRouteImport.update({
    id: '/$orgSlug',
    path: '/$orgSlug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/api/status',
  path: '/api/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigureIndexRoute = ConfigureIndexRouteImport.update({
  id: '/configure/',
  path: '/configure/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevSplatRoute = DevSplatRouteImport.update({
  id: '/dev/$',
  path: '/dev/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsSitemapDotxmlRoute = DocsSitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => DocsRouteRoute,
} as any)
const authenticationAuthPathRoute = authenticationAuthPathRouteImport.update({
  id: '/(authentication)/auth/$path',
  path: '/auth/$path',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrgSlugIndexRoute =
  AuthenticatedOrgSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrgSlugRouteRoute,
  } as any)
const AuthenticatedOnboardingIndexRoute =
  AuthenticatedOnboardingIndexRouteImport.update({
    id: '/onboarding/',
    path: '/onboarding/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrganizationsIndexRoute =
  AuthenticatedOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatSplatRoute = ApiChatSplatRouteImport.update({
  id: '/api/chat/$',
  path: '/api/chat/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSectionIndexRoute = DocsSectionIndexRouteImport.update({
  id: '/$section/',
  path: '/$section/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsApiIndexRoute = DocsApiIndexRouteImport.update({
  id: '/api/',
  path: '/api/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const AuthenticatedOrgSlugAgentsIndexRoute =
  AuthenticatedOrgSlugAgentsIndexRouteImport.update({
    id: '/agents/',
    path: '/agents/',
    getParentRoute: () => AuthenticatedOrgSlugRouteRoute,
  } as any)
const AuthenticatedOrgSlugApiKeysIndexRoute =
  AuthenticatedOrgSlugApiKeysIndexRouteImport.update({
    id: '/api-keys/',
    path: '/api-keys/',
    getParentRoute: () => AuthenticatedOrgSlugRouteRoute,
  } as any)
const AuthenticatedOrgSlugMembersIndexRoute =
  AuthenticatedOrgSlugMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => AuthenticatedOrgSlugRouteRoute,
  } as any)
const AuthenticatedOrgSlugSandboxesIndexRoute =
  AuthenticatedOrgSlugSandboxesIndexRouteImport.update({
    id: '/sandboxes/',
    path: '/sandboxes/',
    getParentRoute: () => AuthenticatedOrgSlugRouteRoute,
  } as any)
const AuthenticatedOrgSlugSettingsIndexRoute =
  AuthenticatedOrgSlugSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedOrgSlugRouteRoute,
  } as any)
const AuthenticatedSettingsAccountIndexRoute =
  AuthenticatedSettingsAccountIndexRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsSecurityIndexRoute =
  AuthenticatedSettingsSecurityIndexRouteImport.update({
    id: '/security/',
    path: '/security/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const DocsSectionPageIndexRoute = DocsSectionPageIndexRouteImport.update({
  id: '/$section/$page/',
  path: '/$section/$page/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const AuthenticatedOrgSlugAgentsAgentIdIndexRoute =
  AuthenticatedOrgSlugAgentsAgentIdIndexRouteImport.update({
    id: '/agents/$agentId/',
    path: '/agents/$agentId/',
    getParentRoute: () => AuthenticatedOrgSlugRouteRoute,
  } as any)
const AuthenticatedOrgSlugAgentsNewIndexRoute =
  AuthenticatedOrgSlugAgentsNewIndexRouteImport.update({
    id: '/agents/new/',
    path: '/agents/new/',
    getParentRoute: () => AuthenticatedOrgSlugRouteRoute,
  } as any)
const AuthenticatedOrgSlugSandboxesSandboxProviderIdIndexRoute =
  AuthenticatedOrgSlugSandboxesSandboxProviderIdIndexRouteImport.update({
    id: '/sandboxes/$sandboxProviderId/',
    path: '/sandboxes/$sandboxProviderId/',
    getParentRoute: () => AuthenticatedOrgSlugRouteRoute,
  } as any)
const AuthenticatedOrgSlugSandboxesNewIndexRoute =
  AuthenticatedOrgSlugSandboxesNewIndexRouteImport.update({
    id: '/sandboxes/new/',
    path: '/sandboxes/new/',
    getParentRoute: () => AuthenticatedOrgSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/$orgSlug': typeof AuthenticatedOrgSlugRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/api/status': typeof ApiStatusRoute
  '/dev/$': typeof DevSplatRoute
  '/docs/sitemap.xml': typeof DocsSitemapDotxmlRoute
  '/configure/': typeof ConfigureIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/auth/$path': typeof authenticationAuthPathRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/chat/$': typeof ApiChatSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/$orgSlug/': typeof AuthenticatedOrgSlugIndexRoute
  '/onboarding/': typeof AuthenticatedOnboardingIndexRoute
  '/organizations/': typeof AuthenticatedOrganizationsIndexRoute
  '/docs/$section/': typeof DocsSectionIndexRoute
  '/docs/api/': typeof DocsApiIndexRoute
  '/$orgSlug/agents/': typeof AuthenticatedOrgSlugAgentsIndexRoute
  '/$orgSlug/api-keys/': typeof AuthenticatedOrgSlugApiKeysIndexRoute
  '/$orgSlug/members/': typeof AuthenticatedOrgSlugMembersIndexRoute
  '/$orgSlug/sandboxes/': typeof AuthenticatedOrgSlugSandboxesIndexRoute
  '/$orgSlug/settings/': typeof AuthenticatedOrgSlugSettingsIndexRoute
  '/settings/account/': typeof AuthenticatedSettingsAccountIndexRoute
  '/settings/security/': typeof AuthenticatedSettingsSecurityIndexRoute
  '/docs/$section/$page/': typeof DocsSectionPageIndexRoute
  '/$orgSlug/agents/$agentId/': typeof AuthenticatedOrgSlugAgentsAgentIdIndexRoute
  '/$orgSlug/agents/new/': typeof AuthenticatedOrgSlugAgentsNewIndexRoute
  '/$orgSlug/sandboxes/$sandboxProviderId/': typeof AuthenticatedOrgSlugSandboxesSandboxProviderIdIndexRoute
  '/$orgSlug/sandboxes/new/': typeof AuthenticatedOrgSlugSandboxesNewIndexRoute
}
export interface FileRoutesByTo {
  '/robots.txt': typeof RobotsDottxtRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/api/status': typeof ApiStatusRoute
  '/dev/$': typeof DevSplatRoute
  '/docs/sitemap.xml': typeof DocsSitemapDotxmlRoute
  '/': typeof AuthenticatedIndexRoute
  '/configure': typeof ConfigureIndexRoute
  '/docs': typeof DocsIndexRoute
  '/auth/$path': typeof authenticationAuthPathRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/chat/$': typeof ApiChatSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/$orgSlug': typeof AuthenticatedOrgSlugIndexRoute
  '/onboarding': typeof AuthenticatedOnboardingIndexRoute
  '/organizations': typeof AuthenticatedOrganizationsIndexRoute
  '/docs/$section': typeof DocsSectionIndexRoute
  '/docs/api': typeof DocsApiIndexRoute
  '/$orgSlug/agents': typeof AuthenticatedOrgSlugAgentsIndexRoute
  '/$orgSlug/api-keys': typeof AuthenticatedOrgSlugApiKeysIndexRoute
  '/$orgSlug/members': typeof AuthenticatedOrgSlugMembersIndexRoute
  '/$orgSlug/sandboxes': typeof AuthenticatedOrgSlugSandboxesIndexRoute
  '/$orgSlug/settings': typeof AuthenticatedOrgSlugSettingsIndexRoute
  '/settings/account': typeof AuthenticatedSettingsAccountIndexRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityIndexRoute
  '/docs/$section/$page': typeof DocsSectionPageIndexRoute
  '/$orgSlug/agents/$agentId': typeof AuthenticatedOrgSlugAgentsAgentIdIndexRoute
  '/$orgSlug/agents/new': typeof AuthenticatedOrgSlugAgentsNewIndexRoute
  '/$orgSlug/sandboxes/$sandboxProviderId': typeof AuthenticatedOrgSlugSandboxesSandboxProviderIdIndexRoute
  '/$orgSlug/sandboxes/new': typeof AuthenticatedOrgSlugSandboxesNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/docs': typeof DocsRouteRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/_authenticated/$orgSlug': typeof AuthenticatedOrgSlugRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/api/status': typeof ApiStatusRoute
  '/dev/$': typeof DevSplatRoute
  '/docs/sitemap.xml': typeof DocsSitemapDotxmlRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/configure/': typeof ConfigureIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/(authentication)/auth/$path': typeof authenticationAuthPathRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/chat/$': typeof ApiChatSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/_authenticated/$orgSlug/': typeof AuthenticatedOrgSlugIndexRoute
  '/_authenticated/onboarding/': typeof AuthenticatedOnboardingIndexRoute
  '/_authenticated/organizations/': typeof AuthenticatedOrganizationsIndexRoute
  '/docs/$section/': typeof DocsSectionIndexRoute
  '/docs/api/': typeof DocsApiIndexRoute
  '/_authenticated/$orgSlug/agents/': typeof AuthenticatedOrgSlugAgentsIndexRoute
  '/_authenticated/$orgSlug/api-keys/': typeof AuthenticatedOrgSlugApiKeysIndexRoute
  '/_authenticated/$orgSlug/members/': typeof AuthenticatedOrgSlugMembersIndexRoute
  '/_authenticated/$orgSlug/sandboxes/': typeof AuthenticatedOrgSlugSandboxesIndexRoute
  '/_authenticated/$orgSlug/settings/': typeof AuthenticatedOrgSlugSettingsIndexRoute
  '/_authenticated/settings/account/': typeof AuthenticatedSettingsAccountIndexRoute
  '/_authenticated/settings/security/': typeof AuthenticatedSettingsSecurityIndexRoute
  '/docs/$section/$page/': typeof DocsSectionPageIndexRoute
  '/_authenticated/$orgSlug/agents/$agentId/': typeof AuthenticatedOrgSlugAgentsAgentIdIndexRoute
  '/_authenticated/$orgSlug/agents/new/': typeof AuthenticatedOrgSlugAgentsNewIndexRoute
  '/_authenticated/$orgSlug/sandboxes/$sandboxProviderId/': typeof AuthenticatedOrgSlugSandboxesSandboxProviderIdIndexRoute
  '/_authenticated/$orgSlug/sandboxes/new/': typeof AuthenticatedOrgSlugSandboxesNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/robots.txt'
    | '/$orgSlug'
    | '/settings'
    | '/api/status'
    | '/dev/$'
    | '/docs/sitemap.xml'
    | '/configure/'
    | '/docs/'
    | '/auth/$path'
    | '/api/auth/$'
    | '/api/chat/$'
    | '/api/v1/$'
    | '/$orgSlug/'
    | '/onboarding/'
    | '/organizations/'
    | '/docs/$section/'
    | '/docs/api/'
    | '/$orgSlug/agents/'
    | '/$orgSlug/api-keys/'
    | '/$orgSlug/members/'
    | '/$orgSlug/sandboxes/'
    | '/$orgSlug/settings/'
    | '/settings/account/'
    | '/settings/security/'
    | '/docs/$section/$page/'
    | '/$orgSlug/agents/$agentId/'
    | '/$orgSlug/agents/new/'
    | '/$orgSlug/sandboxes/$sandboxProviderId/'
    | '/$orgSlug/sandboxes/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/robots.txt'
    | '/settings'
    | '/api/status'
    | '/dev/$'
    | '/docs/sitemap.xml'
    | '/'
    | '/configure'
    | '/docs'
    | '/auth/$path'
    | '/api/auth/$'
    | '/api/chat/$'
    | '/api/v1/$'
    | '/$orgSlug'
    | '/onboarding'
    | '/organizations'
    | '/docs/$section'
    | '/docs/api'
    | '/$orgSlug/agents'
    | '/$orgSlug/api-keys'
    | '/$orgSlug/members'
    | '/$orgSlug/sandboxes'
    | '/$orgSlug/settings'
    | '/settings/account'
    | '/settings/security'
    | '/docs/$section/$page'
    | '/$orgSlug/agents/$agentId'
    | '/$orgSlug/agents/new'
    | '/$orgSlug/sandboxes/$sandboxProviderId'
    | '/$orgSlug/sandboxes/new'
  id:
    | '__root__'
    | '/_authenticated'
    | '/docs'
    | '/robots.txt'
    | '/_authenticated/$orgSlug'
    | '/_authenticated/settings'
    | '/api/status'
    | '/dev/$'
    | '/docs/sitemap.xml'
    | '/_authenticated/'
    | '/configure/'
    | '/docs/'
    | '/(authentication)/auth/$path'
    | '/api/auth/$'
    | '/api/chat/$'
    | '/api/v1/$'
    | '/_authenticated/$orgSlug/'
    | '/_authenticated/onboarding/'
    | '/_authenticated/organizations/'
    | '/docs/$section/'
    | '/docs/api/'
    | '/_authenticated/$orgSlug/agents/'
    | '/_authenticated/$orgSlug/api-keys/'
    | '/_authenticated/$orgSlug/members/'
    | '/_authenticated/$orgSlug/sandboxes/'
    | '/_authenticated/$orgSlug/settings/'
    | '/_authenticated/settings/account/'
    | '/_authenticated/settings/security/'
    | '/docs/$section/$page/'
    | '/_authenticated/$orgSlug/agents/$agentId/'
    | '/_authenticated/$orgSlug/agents/new/'
    | '/_authenticated/$orgSlug/sandboxes/$sandboxProviderId/'
    | '/_authenticated/$orgSlug/sandboxes/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  DocsRouteRoute: typeof DocsRouteRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ApiStatusRoute: typeof ApiStatusRoute
  DevSplatRoute: typeof DevSplatRoute
  ConfigureIndexRoute: typeof ConfigureIndexRoute
  authenticationAuthPathRoute: typeof authenticationAuthPathRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiChatSplatRoute: typeof ApiChatSplatRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$orgSlug': {
      id: '/_authenticated/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/$orgSlug'
      preLoaderRoute: typeof AuthenticatedOrgSlugRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/status': {
      id: '/api/status'
      path: '/api/status'
      fullPath: '/api/status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configure/': {
      id: '/configure/'
      path: '/configure'
      fullPath: '/configure/'
      preLoaderRoute: typeof ConfigureIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/$': {
      id: '/dev/$'
      path: '/dev/$'
      fullPath: '/dev/$'
      preLoaderRoute: typeof DevSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/sitemap.xml': {
      id: '/docs/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/docs/sitemap.xml'
      preLoaderRoute: typeof DocsSitemapDotxmlRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/(authentication)/auth/$path': {
      id: '/(authentication)/auth/$path'
      path: '/auth/$path'
      fullPath: '/auth/$path'
      preLoaderRoute: typeof authenticationAuthPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/$orgSlug/': {
      id: '/_authenticated/$orgSlug/'
      path: '/'
      fullPath: '/$orgSlug/'
      preLoaderRoute: typeof AuthenticatedOrgSlugIndexRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRouteRoute
    }
    '/_authenticated/onboarding/': {
      id: '/_authenticated/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof AuthenticatedOnboardingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organizations/': {
      id: '/_authenticated/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof AuthenticatedOrganizationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/$': {
      id: '/api/chat/$'
      path: '/api/chat/$'
      fullPath: '/api/chat/$'
      preLoaderRoute: typeof ApiChatSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$section/': {
      id: '/docs/$section/'
      path: '/$section'
      fullPath: '/docs/$section/'
      preLoaderRoute: typeof DocsSectionIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/api/': {
      id: '/docs/api/'
      path: '/api'
      fullPath: '/docs/api/'
      preLoaderRoute: typeof DocsApiIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_authenticated/$orgSlug/agents/': {
      id: '/_authenticated/$orgSlug/agents/'
      path: '/agents'
      fullPath: '/$orgSlug/agents/'
      preLoaderRoute: typeof AuthenticatedOrgSlugAgentsIndexRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRouteRoute
    }
    '/_authenticated/$orgSlug/api-keys/': {
      id: '/_authenticated/$orgSlug/api-keys/'
      path: '/api-keys'
      fullPath: '/$orgSlug/api-keys/'
      preLoaderRoute: typeof AuthenticatedOrgSlugApiKeysIndexRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRouteRoute
    }
    '/_authenticated/$orgSlug/members/': {
      id: '/_authenticated/$orgSlug/members/'
      path: '/members'
      fullPath: '/$orgSlug/members/'
      preLoaderRoute: typeof AuthenticatedOrgSlugMembersIndexRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRouteRoute
    }
    '/_authenticated/$orgSlug/sandboxes/': {
      id: '/_authenticated/$orgSlug/sandboxes/'
      path: '/sandboxes'
      fullPath: '/$orgSlug/sandboxes/'
      preLoaderRoute: typeof AuthenticatedOrgSlugSandboxesIndexRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRouteRoute
    }
    '/_authenticated/$orgSlug/settings/': {
      id: '/_authenticated/$orgSlug/settings/'
      path: '/settings'
      fullPath: '/$orgSlug/settings/'
      preLoaderRoute: typeof AuthenticatedOrgSlugSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRouteRoute
    }
    '/_authenticated/settings/account/': {
      id: '/_authenticated/settings/account/'
      path: '/account'
      fullPath: '/settings/account/'
      preLoaderRoute: typeof AuthenticatedSettingsAccountIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/security/': {
      id: '/_authenticated/settings/security/'
      path: '/security'
      fullPath: '/settings/security/'
      preLoaderRoute: typeof AuthenticatedSettingsSecurityIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/docs/$section/$page/': {
      id: '/docs/$section/$page/'
      path: '/$section/$page'
      fullPath: '/docs/$section/$page/'
      preLoaderRoute: typeof DocsSectionPageIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_authenticated/$orgSlug/agents/$agentId/': {
      id: '/_authenticated/$orgSlug/agents/$agentId/'
      path: '/agents/$agentId'
      fullPath: '/$orgSlug/agents/$agentId/'
      preLoaderRoute: typeof AuthenticatedOrgSlugAgentsAgentIdIndexRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRouteRoute
    }
    '/_authenticated/$orgSlug/agents/new/': {
      id: '/_authenticated/$orgSlug/agents/new/'
      path: '/agents/new'
      fullPath: '/$orgSlug/agents/new/'
      preLoaderRoute: typeof AuthenticatedOrgSlugAgentsNewIndexRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRouteRoute
    }
    '/_authenticated/$orgSlug/sandboxes/$sandboxProviderId/': {
      id: '/_authenticated/$orgSlug/sandboxes/$sandboxProviderId/'
      path: '/sandboxes/$sandboxProviderId'
      fullPath: '/$orgSlug/sandboxes/$sandboxProviderId/'
      preLoaderRoute: typeof AuthenticatedOrgSlugSandboxesSandboxProviderIdIndexRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRouteRoute
    }
    '/_authenticated/$orgSlug/sandboxes/new/': {
      id: '/_authenticated/$orgSlug/sandboxes/new/'
      path: '/sandboxes/new'
      fullPath: '/$orgSlug/sandboxes/new/'
      preLoaderRoute: typeof AuthenticatedOrgSlugSandboxesNewIndexRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRouteRoute
    }
  }
}

interface AuthenticatedOrgSlugRouteRouteChildren {
  AuthenticatedOrgSlugIndexRoute: typeof AuthenticatedOrgSlugIndexRoute
  AuthenticatedOrgSlugAgentsIndexRoute: typeof AuthenticatedOrgSlugAgentsIndexRoute
  AuthenticatedOrgSlugApiKeysIndexRoute: typeof AuthenticatedOrgSlugApiKeysIndexRoute
  AuthenticatedOrgSlugMembersIndexRoute: typeof AuthenticatedOrgSlugMembersIndexRoute
  AuthenticatedOrgSlugSandboxesIndexRoute: typeof AuthenticatedOrgSlugSandboxesIndexRoute
  AuthenticatedOrgSlugSettingsIndexRoute: typeof AuthenticatedOrgSlugSettingsIndexRoute
  AuthenticatedOrgSlugAgentsAgentIdIndexRoute: typeof AuthenticatedOrgSlugAgentsAgentIdIndexRoute
  AuthenticatedOrgSlugAgentsNewIndexRoute: typeof AuthenticatedOrgSlugAgentsNewIndexRoute
  AuthenticatedOrgSlugSandboxesSandboxProviderIdIndexRoute: typeof AuthenticatedOrgSlugSandboxesSandboxProviderIdIndexRoute
  AuthenticatedOrgSlugSandboxesNewIndexRoute: typeof AuthenticatedOrgSlugSandboxesNewIndexRoute
}

const AuthenticatedOrgSlugRouteRouteChildren: AuthenticatedOrgSlugRouteRouteChildren =
  {
    AuthenticatedOrgSlugIndexRoute: AuthenticatedOrgSlugIndexRoute,
    AuthenticatedOrgSlugAgentsIndexRoute: AuthenticatedOrgSlugAgentsIndexRoute,
    AuthenticatedOrgSlugApiKeysIndexRoute:
      AuthenticatedOrgSlugApiKeysIndexRoute,
    AuthenticatedOrgSlugMembersIndexRoute:
      AuthenticatedOrgSlugMembersIndexRoute,
    AuthenticatedOrgSlugSandboxesIndexRoute:
      AuthenticatedOrgSlugSandboxesIndexRoute,
    AuthenticatedOrgSlugSettingsIndexRoute:
      AuthenticatedOrgSlugSettingsIndexRoute,
    AuthenticatedOrgSlugAgentsAgentIdIndexRoute:
      AuthenticatedOrgSlugAgentsAgentIdIndexRoute,
    AuthenticatedOrgSlugAgentsNewIndexRoute:
      AuthenticatedOrgSlugAgentsNewIndexRoute,
    AuthenticatedOrgSlugSandboxesSandboxProviderIdIndexRoute:
      AuthenticatedOrgSlugSandboxesSandboxProviderIdIndexRoute,
    AuthenticatedOrgSlugSandboxesNewIndexRoute:
      AuthenticatedOrgSlugSandboxesNewIndexRoute,
  }

const AuthenticatedOrgSlugRouteRouteWithChildren =
  AuthenticatedOrgSlugRouteRoute._addFileChildren(
    AuthenticatedOrgSlugRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountIndexRoute: typeof AuthenticatedSettingsAccountIndexRoute
  AuthenticatedSettingsSecurityIndexRoute: typeof AuthenticatedSettingsSecurityIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountIndexRoute:
      AuthenticatedSettingsAccountIndexRoute,
    AuthenticatedSettingsSecurityIndexRoute:
      AuthenticatedSettingsSecurityIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOrgSlugRouteRoute: typeof AuthenticatedOrgSlugRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedOnboardingIndexRoute: typeof AuthenticatedOnboardingIndexRoute
  AuthenticatedOrganizationsIndexRoute: typeof AuthenticatedOrganizationsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOrgSlugRouteRoute: AuthenticatedOrgSlugRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedOnboardingIndexRoute: AuthenticatedOnboardingIndexRoute,
  AuthenticatedOrganizationsIndexRoute: AuthenticatedOrganizationsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface DocsRouteRouteChildren {
  DocsSitemapDotxmlRoute: typeof DocsSitemapDotxmlRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsSectionIndexRoute: typeof DocsSectionIndexRoute
  DocsApiIndexRoute: typeof DocsApiIndexRoute
  DocsSectionPageIndexRoute: typeof DocsSectionPageIndexRoute
}

const DocsRouteRouteChildren: DocsRouteRouteChildren = {
  DocsSitemapDotxmlRoute: DocsSitemapDotxmlRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsSectionIndexRoute: DocsSectionIndexRoute,
  DocsApiIndexRoute: DocsApiIndexRoute,
  DocsSectionPageIndexRoute: DocsSectionPageIndexRoute,
}

const DocsRouteRouteWithChildren = DocsRouteRoute._addFileChildren(
  DocsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  DocsRouteRoute: DocsRouteRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ApiStatusRoute: ApiStatusRoute,
  DevSplatRoute: DevSplatRoute,
  ConfigureIndexRoute: ConfigureIndexRoute,
  authenticationAuthPathRoute: authenticationAuthPathRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiChatSplatRoute: ApiChatSplatRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
