packages:
  - apps/*

allowBuilds:
  esbuild: true
  lightningcss: true
  msgpackr-extract: false
  sharp: true
  workerd: true

catalogMode: prefer

catalog:
  "@types/node": ^22
  knip: ^6.32.0
  typescript: ^6.0.3
  vite: npm:@voidzero-dev/vite-plus-core@0.2.5
  vite-plus: 0.2.5
  wrangler: ^4.112.0

overrides:
  vite: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
