/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ConfigureRouteRouteImport } from './routes/configure/route'
import { Route as DocsRouteRouteImport } from './routes/docs/route'
import { Route as DocsDotmdRouteImport } from './routes/docs[.]md'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedOrgSlugRouteRouteImport } from './routes/_authenticated/$orgSlug/route'
import { Route as AuthenticatedUserRouteRouteImport } from './routes/_authenticated/_user/route'
import { Route as ApiStatusRouteImport } from './routes/api/status'
import { Route as ConfigureIndexRouteImport } from './routes/configure/index'
import { Route as DevSplatRouteImport } from './routes/dev/$'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsSitemapDotxmlRouteImport } from './routes/docs/sitemap[.]xml'
import { Route as authenticationAuthPathRouteImport } from './routes/(authentication)/auth/$path'
import { Route as AuthenticatedOrgSlugIndexRouteImport } from './routes/_authenticated/$orgSlug/index'
import { Route as AuthenticatedChar126SplatRouteImport } from './routes/_authenticated/~/$'
import { Route as ApiAstralbeamTokenRouteImport } from './routes/api/astralbeam/token'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiChatSplatRouteImport } from './routes/api/chat/$'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'
import { Route as DocsSectionIndexRouteImport } from './routes/docs/$section/index'
import { Route as DocsApiIndexRouteImport } from './routes/docs/api/index'
import { Route as AuthenticatedOrgSlugAgentsIndexRouteImport } from './routes/_authenticated/$orgSlug/agents/index'
import { Route as AuthenticatedOrgSlugApiKeysIndexRouteImport } from './routes/_authenticated/$orgSlug/api-keys/index'
import { Route as AuthenticatedOrgSlugMembersIndexRouteImport } from './routes/_authenticated/$orgSlug/members/index'
import { Route as AuthenticatedOrgSlugModelsIndexRouteImport } from './routes/_authenticated/$orgSlug/models/index'
import { Route as AuthenticatedOrgSlugSandboxesIndexRouteImport } from './routes/_authenticated/$orgSlug/sandboxes/index'
import { Route as AuthenticatedOrgSlugSettingsIndexRouteImport } from './routes/_authenticated/$orgSlug/settings/index'
import { Route as AuthenticatedOrgSlugTenantUsersIndexRouteImport } from './routes/_authenticated/$orgSlug/tenant-users/index'
import { Route as AuthenticatedOrgSlugTenantsIndexRouteImport } from './routes/_authenticated/$orgSlug/tenants/index'
import { Route as AuthenticatedUserOnboardingIndexRouteImport } from './routes/_authenticated/_user/onboarding/index'
import { Route as AuthenticatedUserOrganizationsIndexRouteImport } from './routes/_authenticated/_user/organizations/index'
import { Route as AuthenticatedUserSettingsIndexRouteImport } from './routes/_authenticated/_user/settings/index'
import { Route as DocsSectionPageIndexRouteImport } from './routes/docs/$section/$page/index'
import { Route as DocsSectionChar123pageChar125DotmdIndexRouteImport } from './routes/docs/$section/{$page}[.]md/index'
import { Route as AuthenticatedOrgSlugAgentsAgentIdIndexRouteImport } from './routes/_authenticated/$orgSlug/agents/$agentId/index'
import { Route as AuthenticatedOrgSlugAgentsNewIndexRouteImport } from './routes/_authenticated/$orgSlug/agents/new/index'
import { Route as AuthenticatedOrgSlugModelsModelProviderIdIndexRouteImport } from './routes/_authenticated/$orgSlug/models/$modelProviderId/index'
import { Route as AuthenticatedOrgSlugModelsNewIndexRouteImport } from './routes/_authenticated/$orgSlug/models/new/index'
import { Route as AuthenticatedOrgSlugSandboxesSandboxProviderIdIndexRouteImport } from './routes/_authenticated/$orgSlug/sandboxes/$sandboxProviderId/index'
import { Route as AuthenticatedOrgSlugSandboxesNewIndexRouteImport } from './routes/_authenticated/$orgSlug/sandboxes/new/index'
import { Route as AuthenticatedUserSettingsAccountIndexRouteImport } from './routes/_authenticated/_user/settings/account/index'
import { Route as AuthenticatedUserSettingsSecurityIndexRouteImport } from './routes/_authenticated/_user/settings/security/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigureRouteRoute = ConfigureRouteRouteImport.update({
  id: '/configure',
  path: '/configure',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRouteRoute = DocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsDotmdRoute = DocsDotmdRouteImport.update({
  id: '/docs.md',
  path: '/docs.md',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrgSlugRouteRoute =
  AuthenticatedOrgSlugRouteRouteImport.update({
    id: '/$orgSlug',
    path: '/$orgSlug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUserRouteRoute = AuthenticatedUserRouteRouteImport.update({
  id: '/_user',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/api/status',
  path: '/api/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigureIndexRoute = ConfigureIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConfigureRouteRoute,
} as any)
const DevSplatRoute = DevSplatRouteImport.update({
  id: '/dev/$',
  path: '/dev/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsSitemapDotxmlRoute = DocsSitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => DocsRouteRoute,
} as any)
const authenticationAuthPathRoute = authenticationAuthPathRouteImport.update({
  id: '/(authentication)/auth/$path',
  path: '/auth/$path',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrgSlugIndexRoute =
  AuthenticatedOrgSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrgSlugRouteRoute,
  } as any)
const AuthenticatedChar126SplatRoute =
  AuthenticatedChar126SplatRouteImport.update({
    id: '/~/$',
    path: '/~/$',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiAstralbeamTokenRoute = ApiAstralbeamTokenRouteImport.update({
  id: '/api/astralbeam/token',
  path: '/api/astralbeam/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatSplatRoute = ApiChatSplatRouteImport.update({
  id: '/api/chat/$',
  path: '/api/chat/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSectionIndexRoute = DocsSectionIndexRouteImport.update({
  id: '/$section/',
  path: '/$section/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsApiIndexRoute = DocsApiIndexRouteImport.update({
  id: '/api/',
  path: '/api/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const AuthenticatedOrgSlugAgentsIndexRoute =
  AuthenticatedOrgSlugAgentsIndexRouteImport.update({
    id: '/agents/',
    path: '/agents/',
    getParentRoute: () => AuthenticatedOrgSlugRouteRoute,
  } as any)
const AuthenticatedOrgSlugApiKeysIndexRoute =
  AuthenticatedOrgSlugApiKeysIndexRouteImport.update({
    id: '/api-keys/',
    path: '/api-keys/',
    getParentRoute: () => AuthenticatedOrgSlugRouteRoute,
  } as any)
const AuthenticatedOrgSlugMembersIndexRoute =
  AuthenticatedOrgSlugMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => AuthenticatedOrgSlugRouteRoute,
  } as any)
const AuthenticatedOrgSlugModelsIndexRoute =
  AuthenticatedOrgSlugModelsIndexRouteImport.update({
    id: '/models/',
    path: '/models/',
    getParentRoute: () => AuthenticatedOrgSlugRouteRoute,
  } as any)
const AuthenticatedOrgSlugSandboxesIndexRoute =
  AuthenticatedOrgSlugSandboxesIndexRouteImport.update({
    id: '/sandboxes/',
    path: '/sandboxes/',
    getParentRoute: () => AuthenticatedOrgSlugRouteRoute,
  } as any)
const AuthenticatedOrgSlugSettingsIndexRoute =
  AuthenticatedOrgSlugSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedOrgSlugRouteRoute,
  } as any)
const AuthenticatedOrgSlugTenantUsersIndexRoute =
  AuthenticatedOrgSlugTenantUsersIndexRouteImport.update({
    id: '/tenant-users/',
    path: '/tenant-users/',
    getParentRoute: () => AuthenticatedOrgSlugRouteRoute,
  } as any)
const AuthenticatedOrgSlugTenantsIndexRoute =
  AuthenticatedOrgSlugTenantsIndexRouteImport.update({
    id: '/tenants/',
    path: '/tenants/',
    getParentRoute: () => AuthenticatedOrgSlugRouteRoute,
  } as any)
const AuthenticatedUserOnboardingIndexRoute =
  AuthenticatedUserOnboardingIndexRouteImport.update({
    id: '/onboarding/',
    path: '/onboarding/',
    getParentRoute: () => AuthenticatedUserRouteRoute,
  } as any)
const AuthenticatedUserOrganizationsIndexRoute =
  AuthenticatedUserOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => AuthenticatedUserRouteRoute,
  } as any)
const AuthenticatedUserSettingsIndexRoute =
  AuthenticatedUserSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedUserRouteRoute,
  } as any)
const DocsSectionPageIndexRoute = DocsSectionPageIndexRouteImport.update({
  id: '/$section/$page/',
  path: '/$section/$page/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsSectionChar123pageChar125DotmdIndexRoute =
  DocsSectionChar123pageChar125DotmdIndexRouteImport.update({
    id: '/$section/{$page}.md/',
    path: '/$section/{$page}.md/',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const AuthenticatedOrgSlugAgentsAgentIdIndexRoute =
  AuthenticatedOrgSlugAgentsAgentIdIndexRouteImport.update({
    id: '/agents/$agentId/',
    path: '/agents/$agentId/',
    getParentRoute: () => AuthenticatedOrgSlugRouteRoute,
  } as any)
const AuthenticatedOrgSlugAgentsNewIndexRoute =
  AuthenticatedOrgSlugAgentsNewIndexRouteImport.update({
    id: '/agents/new/',
    path: '/agents/new/',
    getParentRoute: () => AuthenticatedOrgSlugRouteRoute,
  } as any)
const AuthenticatedOrgSlugModelsModelProviderIdIndexRoute =
  AuthenticatedOrgSlugModelsModelProviderIdIndexRouteImport.update({
    id: '/models/$modelProviderId/',
    path: '/models/$modelProviderId/',
    getParentRoute: () => AuthenticatedOrgSlugRouteRoute,
  } as any)
const AuthenticatedOrgSlugModelsNewIndexRoute =
  AuthenticatedOrgSlugModelsNewIndexRouteImport.update({
    id: '/models/new/',
    path: '/models/new/',
    getParentRoute: () => AuthenticatedOrgSlugRouteRoute,
  } as any)
const AuthenticatedOrgSlugSandboxesSandboxProviderIdIndexRoute =
  AuthenticatedOrgSlugSandboxesSandboxProviderIdIndexRouteImport.update({
    id: '/sandboxes/$sandboxProviderId/',
    path: '/sandboxes/$sandboxProviderId/',
    getParentRoute: () => AuthenticatedOrgSlugRouteRoute,
  } as any)
const AuthenticatedOrgSlugSandboxesNewIndexRoute =
  AuthenticatedOrgSlugSandboxesNewIndexRouteImport.update({
    id: '/sandboxes/new/',
    path: '/sandboxes/new/',
    getParentRoute: () => AuthenticatedOrgSlugRouteRoute,
  } as any)
const AuthenticatedUserSettingsAccountIndexRoute =
  AuthenticatedUserSettingsAccountIndexRouteImport.update({
    id: '/settings/account/',
    path: '/settings/account/',
    getParentRoute: () => AuthenticatedUserRouteRoute,
  } as any)
const AuthenticatedUserSettingsSecurityIndexRoute =
  AuthenticatedUserSettingsSecurityIndexRouteImport.update({
    id: '/settings/security/',
    path: '/settings/security/',
    getParentRoute: () => AuthenticatedUserRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/configure': typeof ConfigureRouteRouteWithChildren
  '/docs': typeof DocsRouteRouteWithChildren
  '/docs.md': typeof DocsDotmdRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/$orgSlug': typeof AuthenticatedOrgSlugRouteRouteWithChildren
  '/api/status': typeof ApiStatusRoute
  '/dev/$': typeof DevSplatRoute
  '/docs/sitemap.xml': typeof DocsSitemapDotxmlRoute
  '/configure/': typeof ConfigureIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/auth/$path': typeof authenticationAuthPathRoute
  '/~/$': typeof AuthenticatedChar126SplatRoute
  '/api/astralbeam/token': typeof ApiAstralbeamTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/chat/$': typeof ApiChatSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/$orgSlug/': typeof AuthenticatedOrgSlugIndexRoute
  '/docs/$section/': typeof DocsSectionIndexRoute
  '/docs/api/': typeof DocsApiIndexRoute
  '/$orgSlug/agents/': typeof AuthenticatedOrgSlugAgentsIndexRoute
  '/$orgSlug/api-keys/': typeof AuthenticatedOrgSlugApiKeysIndexRoute
  '/$orgSlug/members/': typeof AuthenticatedOrgSlugMembersIndexRoute
  '/$orgSlug/models/': typeof AuthenticatedOrgSlugModelsIndexRoute
  '/$orgSlug/sandboxes/': typeof AuthenticatedOrgSlugSandboxesIndexRoute
  '/$orgSlug/settings/': typeof AuthenticatedOrgSlugSettingsIndexRoute
  '/$orgSlug/tenant-users/': typeof AuthenticatedOrgSlugTenantUsersIndexRoute
  '/$orgSlug/tenants/': typeof AuthenticatedOrgSlugTenantsIndexRoute
  '/onboarding/': typeof AuthenticatedUserOnboardingIndexRoute
  '/organizations/': typeof AuthenticatedUserOrganizationsIndexRoute
  '/settings/': typeof AuthenticatedUserSettingsIndexRoute
  '/docs/$section/$page/': typeof DocsSectionPageIndexRoute
  '/docs/$section/{$page}.md/': typeof DocsSectionChar123pageChar125DotmdIndexRoute
  '/$orgSlug/agents/$agentId/': typeof AuthenticatedOrgSlugAgentsAgentIdIndexRoute
  '/$orgSlug/agents/new/': typeof AuthenticatedOrgSlugAgentsNewIndexRoute
  '/$orgSlug/models/$modelProviderId/': typeof AuthenticatedOrgSlugModelsModelProviderIdIndexRoute
  '/$orgSlug/models/new/': typeof AuthenticatedOrgSlugModelsNewIndexRoute
  '/$orgSlug/sandboxes/$sandboxProviderId/': typeof AuthenticatedOrgSlugSandboxesSandboxProviderIdIndexRoute
  '/$orgSlug/sandboxes/new/': typeof AuthenticatedOrgSlugSandboxesNewIndexRoute
  '/settings/account/': typeof AuthenticatedUserSettingsAccountIndexRoute
  '/settings/security/': typeof AuthenticatedUserSettingsSecurityIndexRoute
}
export interface FileRoutesByTo {
  '/docs.md': typeof DocsDotmdRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/status': typeof ApiStatusRoute
  '/dev/$': typeof DevSplatRoute
  '/docs/sitemap.xml': typeof DocsSitemapDotxmlRoute
  '/configure': typeof ConfigureIndexRoute
  '/docs': typeof DocsIndexRoute
  '/auth/$path': typeof authenticationAuthPathRoute
  '/~/$': typeof AuthenticatedChar126SplatRoute
  '/api/astralbeam/token': typeof ApiAstralbeamTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/chat/$': typeof ApiChatSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/$orgSlug': typeof AuthenticatedOrgSlugIndexRoute
  '/docs/$section': typeof DocsSectionIndexRoute
  '/docs/api': typeof DocsApiIndexRoute
  '/$orgSlug/agents': typeof AuthenticatedOrgSlugAgentsIndexRoute
  '/$orgSlug/api-keys': typeof AuthenticatedOrgSlugApiKeysIndexRoute
  '/$orgSlug/members': typeof AuthenticatedOrgSlugMembersIndexRoute
  '/$orgSlug/models': typeof AuthenticatedOrgSlugModelsIndexRoute
  '/$orgSlug/sandboxes': typeof AuthenticatedOrgSlugSandboxesIndexRoute
  '/$orgSlug/settings': typeof AuthenticatedOrgSlugSettingsIndexRoute
  '/$orgSlug/tenant-users': typeof AuthenticatedOrgSlugTenantUsersIndexRoute
  '/$orgSlug/tenants': typeof AuthenticatedOrgSlugTenantsIndexRoute
  '/onboarding': typeof AuthenticatedUserOnboardingIndexRoute
  '/organizations': typeof AuthenticatedUserOrganizationsIndexRoute
  '/settings': typeof AuthenticatedUserSettingsIndexRoute
  '/docs/$section/$page': typeof DocsSectionPageIndexRoute
  '/docs/$section/{$page}.md': typeof DocsSectionChar123pageChar125DotmdIndexRoute
  '/$orgSlug/agents/$agentId': typeof AuthenticatedOrgSlugAgentsAgentIdIndexRoute
  '/$orgSlug/agents/new': typeof AuthenticatedOrgSlugAgentsNewIndexRoute
  '/$orgSlug/models/$modelProviderId': typeof AuthenticatedOrgSlugModelsModelProviderIdIndexRoute
  '/$orgSlug/models/new': typeof AuthenticatedOrgSlugModelsNewIndexRoute
  '/$orgSlug/sandboxes/$sandboxProviderId': typeof AuthenticatedOrgSlugSandboxesSandboxProviderIdIndexRoute
  '/$orgSlug/sandboxes/new': typeof AuthenticatedOrgSlugSandboxesNewIndexRoute
  '/settings/account': typeof AuthenticatedUserSettingsAccountIndexRoute
  '/settings/security': typeof AuthenticatedUserSettingsSecurityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/configure': typeof ConfigureRouteRouteWithChildren
  '/docs': typeof DocsRouteRouteWithChildren
  '/docs.md': typeof DocsDotmdRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/_authenticated/$orgSlug': typeof AuthenticatedOrgSlugRouteRouteWithChildren
  '/_authenticated/_user': typeof AuthenticatedUserRouteRouteWithChildren
  '/api/status': typeof ApiStatusRoute
  '/dev/$': typeof DevSplatRoute
  '/docs/sitemap.xml': typeof DocsSitemapDotxmlRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/configure/': typeof ConfigureIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/(authentication)/auth/$path': typeof authenticationAuthPathRoute
  '/_authenticated/~/$': typeof AuthenticatedChar126SplatRoute
  '/api/astralbeam/token': typeof ApiAstralbeamTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/chat/$': typeof ApiChatSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/_authenticated/$orgSlug/': typeof AuthenticatedOrgSlugIndexRoute
  '/docs/$section/': typeof DocsSectionIndexRoute
  '/docs/api/': typeof DocsApiIndexRoute
  '/_authenticated/$orgSlug/agents/': typeof AuthenticatedOrgSlugAgentsIndexRoute
  '/_authenticated/$orgSlug/api-keys/': typeof AuthenticatedOrgSlugApiKeysIndexRoute
  '/_authenticated/$orgSlug/members/': typeof AuthenticatedOrgSlugMembersIndexRoute
  '/_authenticated/$orgSlug/models/': typeof AuthenticatedOrgSlugModelsIndexRoute
  '/_authenticated/$orgSlug/sandboxes/': typeof AuthenticatedOrgSlugSandboxesIndexRoute
  '/_authenticated/$orgSlug/settings/': typeof AuthenticatedOrgSlugSettingsIndexRoute
  '/_authenticated/$orgSlug/tenant-users/': typeof AuthenticatedOrgSlugTenantUsersIndexRoute
  '/_authenticated/$orgSlug/tenants/': typeof AuthenticatedOrgSlugTenantsIndexRoute
  '/_authenticated/_user/onboarding/': typeof AuthenticatedUserOnboardingIndexRoute
  '/_authenticated/_user/organizations/': typeof AuthenticatedUserOrganizationsIndexRoute
  '/_authenticated/_user/settings/': typeof AuthenticatedUserSettingsIndexRoute
  '/docs/$section/$page/': typeof DocsSectionPageIndexRoute
  '/docs/$section/{$page}.md/': typeof DocsSectionChar123pageChar125DotmdIndexRoute
  '/_authenticated/$orgSlug/agents/$agentId/': typeof AuthenticatedOrgSlugAgentsAgentIdIndexRoute
  '/_authenticated/$orgSlug/agents/new/': typeof AuthenticatedOrgSlugAgentsNewIndexRoute
  '/_authenticated/$orgSlug/models/$modelProviderId/': typeof AuthenticatedOrgSlugModelsModelProviderIdIndexRoute
  '/_authenticated/$orgSlug/models/new/': typeof AuthenticatedOrgSlugModelsNewIndexRoute
  '/_authenticated/$orgSlug/sandboxes/$sandboxProviderId/': typeof AuthenticatedOrgSlugSandboxesSandboxProviderIdIndexRoute
  '/_authenticated/$orgSlug/sandboxes/new/': typeof AuthenticatedOrgSlugSandboxesNewIndexRoute
  '/_authenticated/_user/settings/account/': typeof AuthenticatedUserSettingsAccountIndexRoute
  '/_authenticated/_user/settings/security/': typeof AuthenticatedUserSettingsSecurityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configure'
    | '/docs'
    | '/docs.md'
    | '/robots.txt'
    | '/$orgSlug'
    | '/api/status'
    | '/dev/$'
    | '/docs/sitemap.xml'
    | '/configure/'
    | '/docs/'
    | '/auth/$path'
    | '/~/$'
    | '/api/astralbeam/token'
    | '/api/auth/$'
    | '/api/chat/$'
    | '/api/v1/$'
    | '/$orgSlug/'
    | '/docs/$section/'
    | '/docs/api/'
    | '/$orgSlug/agents/'
    | '/$orgSlug/api-keys/'
    | '/$orgSlug/members/'
    | '/$orgSlug/models/'
    | '/$orgSlug/sandboxes/'
    | '/$orgSlug/settings/'
    | '/$orgSlug/tenant-users/'
    | '/$orgSlug/tenants/'
    | '/onboarding/'
    | '/organizations/'
    | '/settings/'
    | '/docs/$section/$page/'
    | '/docs/$section/{$page}.md/'
    | '/$orgSlug/agents/$agentId/'
    | '/$orgSlug/agents/new/'
    | '/$orgSlug/models/$modelProviderId/'
    | '/$orgSlug/models/new/'
    | '/$orgSlug/sandboxes/$sandboxProviderId/'
    | '/$orgSlug/sandboxes/new/'
    | '/settings/account/'
    | '/settings/security/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/docs.md'
    | '/robots.txt'
    | '/'
    | '/api/status'
    | '/dev/$'
    | '/docs/sitemap.xml'
    | '/configure'
    | '/docs'
    | '/auth/$path'
    | '/~/$'
    | '/api/astralbeam/token'
    | '/api/auth/$'
    | '/api/chat/$'
    | '/api/v1/$'
    | '/$orgSlug'
    | '/docs/$section'
    | '/docs/api'
    | '/$orgSlug/agents'
    | '/$orgSlug/api-keys'
    | '/$orgSlug/members'
    | '/$orgSlug/models'
    | '/$orgSlug/sandboxes'
    | '/$orgSlug/settings'
    | '/$orgSlug/tenant-users'
    | '/$orgSlug/tenants'
    | '/onboarding'
    | '/organizations'
    | '/settings'
    | '/docs/$section/$page'
    | '/docs/$section/{$page}.md'
    | '/$orgSlug/agents/$agentId'
    | '/$orgSlug/agents/new'
    | '/$orgSlug/models/$modelProviderId'
    | '/$orgSlug/models/new'
    | '/$orgSlug/sandboxes/$sandboxProviderId'
    | '/$orgSlug/sandboxes/new'
    | '/settings/account'
    | '/settings/security'
  id:
    | '__root__'
    | '/_authenticated'
    | '/configure'
    | '/docs'
    | '/docs.md'
    | '/robots.txt'
    | '/_authenticated/$orgSlug'
    | '/_authenticated/_user'
    | '/api/status'
    | '/dev/$'
    | '/docs/sitemap.xml'
    | '/_authenticated/'
    | '/configure/'
    | '/docs/'
    | '/(authentication)/auth/$path'
    | '/_authenticated/~/$'
    | '/api/astralbeam/token'
    | '/api/auth/$'
    | '/api/chat/$'
    | '/api/v1/$'
    | '/_authenticated/$orgSlug/'
    | '/docs/$section/'
    | '/docs/api/'
    | '/_authenticated/$orgSlug/agents/'
    | '/_authenticated/$orgSlug/api-keys/'
    | '/_authenticated/$orgSlug/members/'
    | '/_authenticated/$orgSlug/models/'
    | '/_authenticated/$orgSlug/sandboxes/'
    | '/_authenticated/$orgSlug/settings/'
    | '/_authenticated/$orgSlug/tenant-users/'
    | '/_authenticated/$orgSlug/tenants/'
    | '/_authenticated/_user/onboarding/'
    | '/_authenticated/_user/organizations/'
    | '/_authenticated/_user/settings/'
    | '/docs/$section/$page/'
    | '/docs/$section/{$page}.md/'
    | '/_authenticated/$orgSlug/agents/$agentId/'
    | '/_authenticated/$orgSlug/agents/new/'
    | '/_authenticated/$orgSlug/models/$modelProviderId/'
    | '/_authenticated/$orgSlug/models/new/'
    | '/_authenticated/$orgSlug/sandboxes/$sandboxProviderId/'
    | '/_authenticated/$orgSlug/sandboxes/new/'
    | '/_authenticated/_user/settings/account/'
    | '/_authenticated/_user/settings/security/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ConfigureRouteRoute: typeof ConfigureRouteRouteWithChildren
  DocsRouteRoute: typeof DocsRouteRouteWithChildren
  DocsDotmdRoute: typeof DocsDotmdRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ApiStatusRoute: typeof ApiStatusRoute
  DevSplatRoute: typeof DevSplatRoute
  authenticationAuthPathRoute: typeof authenticationAuthPathRoute
  ApiAstralbeamTokenRoute: typeof ApiAstralbeamTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiChatSplatRoute: typeof ApiChatSplatRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configure': {
      id: '/configure'
      path: '/configure'
      fullPath: '/configure'
      preLoaderRoute: typeof ConfigureRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs.md': {
      id: '/docs.md'
      path: '/docs.md'
      fullPath: '/docs.md'
      preLoaderRoute: typeof DocsDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$orgSlug': {
      id: '/_authenticated/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/$orgSlug'
      preLoaderRoute: typeof AuthenticatedOrgSlugRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_user': {
      id: '/_authenticated/_user'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedUserRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/status': {
      id: '/api/status'
      path: '/api/status'
      fullPath: '/api/status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configure/': {
      id: '/configure/'
      path: '/'
      fullPath: '/configure/'
      preLoaderRoute: typeof ConfigureIndexRouteImport
      parentRoute: typeof ConfigureRouteRoute
    }
    '/dev/$': {
      id: '/dev/$'
      path: '/dev/$'
      fullPath: '/dev/$'
      preLoaderRoute: typeof DevSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/sitemap.xml': {
      id: '/docs/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/docs/sitemap.xml'
      preLoaderRoute: typeof DocsSitemapDotxmlRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/(authentication)/auth/$path': {
      id: '/(authentication)/auth/$path'
      path: '/auth/$path'
      fullPath: '/auth/$path'
      preLoaderRoute: typeof authenticationAuthPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/$orgSlug/': {
      id: '/_authenticated/$orgSlug/'
      path: '/'
      fullPath: '/$orgSlug/'
      preLoaderRoute: typeof AuthenticatedOrgSlugIndexRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRouteRoute
    }
    '/_authenticated/~/$': {
      id: '/_authenticated/~/$'
      path: '/~/$'
      fullPath: '/~/$'
      preLoaderRoute: typeof AuthenticatedChar126SplatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/astralbeam/token': {
      id: '/api/astralbeam/token'
      path: '/api/astralbeam/token'
      fullPath: '/api/astralbeam/token'
      preLoaderRoute: typeof ApiAstralbeamTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/$': {
      id: '/api/chat/$'
      path: '/api/chat/$'
      fullPath: '/api/chat/$'
      preLoaderRoute: typeof ApiChatSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$section/': {
      id: '/docs/$section/'
      path: '/$section'
      fullPath: '/docs/$section/'
      preLoaderRoute: typeof DocsSectionIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/api/': {
      id: '/docs/api/'
      path: '/api'
      fullPath: '/docs/api/'
      preLoaderRoute: typeof DocsApiIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_authenticated/$orgSlug/agents/': {
      id: '/_authenticated/$orgSlug/agents/'
      path: '/agents'
      fullPath: '/$orgSlug/agents/'
      preLoaderRoute: typeof AuthenticatedOrgSlugAgentsIndexRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRouteRoute
    }
    '/_authenticated/$orgSlug/api-keys/': {
      id: '/_authenticated/$orgSlug/api-keys/'
      path: '/api-keys'
      fullPath: '/$orgSlug/api-keys/'
      preLoaderRoute: typeof AuthenticatedOrgSlugApiKeysIndexRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRouteRoute
    }
    '/_authenticated/$orgSlug/members/': {
      id: '/_authenticated/$orgSlug/members/'
      path: '/members'
      fullPath: '/$orgSlug/members/'
      preLoaderRoute: typeof AuthenticatedOrgSlugMembersIndexRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRouteRoute
    }
    '/_authenticated/$orgSlug/models/': {
      id: '/_authenticated/$orgSlug/models/'
      path: '/models'
      fullPath: '/$orgSlug/models/'
      preLoaderRoute: typeof AuthenticatedOrgSlugModelsIndexRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRouteRoute
    }
    '/_authenticated/$orgSlug/sandboxes/': {
      id: '/_authenticated/$orgSlug/sandboxes/'
      path: '/sandboxes'
      fullPath: '/$orgSlug/sandboxes/'
      preLoaderRoute: typeof AuthenticatedOrgSlugSandboxesIndexRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRouteRoute
    }
    '/_authenticated/$orgSlug/settings/': {
      id: '/_authenticated/$orgSlug/settings/'
      path: '/settings'
      fullPath: '/$orgSlug/settings/'
      preLoaderRoute: typeof AuthenticatedOrgSlugSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRouteRoute
    }
    '/_authenticated/$orgSlug/tenant-users/': {
      id: '/_authenticated/$orgSlug/tenant-users/'
      path: '/tenant-users'
      fullPath: '/$orgSlug/tenant-users/'
      preLoaderRoute: typeof AuthenticatedOrgSlugTenantUsersIndexRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRouteRoute
    }
    '/_authenticated/$orgSlug/tenants/': {
      id: '/_authenticated/$orgSlug/tenants/'
      path: '/tenants'
      fullPath: '/$orgSlug/tenants/'
      preLoaderRoute: typeof AuthenticatedOrgSlugTenantsIndexRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRouteRoute
    }
    '/_authenticated/_user/onboarding/': {
      id: '/_authenticated/_user/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof AuthenticatedUserOnboardingIndexRouteImport
      parentRoute: typeof AuthenticatedUserRouteRoute
    }
    '/_authenticated/_user/organizations/': {
      id: '/_authenticated/_user/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof AuthenticatedUserOrganizationsIndexRouteImport
      parentRoute: typeof AuthenticatedUserRouteRoute
    }
    '/_authenticated/_user/settings/': {
      id: '/_authenticated/_user/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedUserSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedUserRouteRoute
    }
    '/docs/$section/$page/': {
      id: '/docs/$section/$page/'
      path: '/$section/$page'
      fullPath: '/docs/$section/$page/'
      preLoaderRoute: typeof DocsSectionPageIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/$section/{$page}.md/': {
      id: '/docs/$section/{$page}.md/'
      path: '/$section/{$page}.md'
      fullPath: '/docs/$section/{$page}.md/'
      preLoaderRoute: typeof DocsSectionChar123pageChar125DotmdIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_authenticated/$orgSlug/agents/$agentId/': {
      id: '/_authenticated/$orgSlug/agents/$agentId/'
      path: '/agents/$agentId'
      fullPath: '/$orgSlug/agents/$agentId/'
      preLoaderRoute: typeof AuthenticatedOrgSlugAgentsAgentIdIndexRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRouteRoute
    }
    '/_authenticated/$orgSlug/agents/new/': {
      id: '/_authenticated/$orgSlug/agents/new/'
      path: '/agents/new'
      fullPath: '/$orgSlug/agents/new/'
      preLoaderRoute: typeof AuthenticatedOrgSlugAgentsNewIndexRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRouteRoute
    }
    '/_authenticated/$orgSlug/models/$modelProviderId/': {
      id: '/_authenticated/$orgSlug/models/$modelProviderId/'
      path: '/models/$modelProviderId'
      fullPath: '/$orgSlug/models/$modelProviderId/'
      preLoaderRoute: typeof AuthenticatedOrgSlugModelsModelProviderIdIndexRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRouteRoute
    }
    '/_authenticated/$orgSlug/models/new/': {
      id: '/_authenticated/$orgSlug/models/new/'
      path: '/models/new'
      fullPath: '/$orgSlug/models/new/'
      preLoaderRoute: typeof AuthenticatedOrgSlugModelsNewIndexRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRouteRoute
    }
    '/_authenticated/$orgSlug/sandboxes/$sandboxProviderId/': {
      id: '/_authenticated/$orgSlug/sandboxes/$sandboxProviderId/'
      path: '/sandboxes/$sandboxProviderId'
      fullPath: '/$orgSlug/sandboxes/$sandboxProviderId/'
      preLoaderRoute: typeof AuthenticatedOrgSlugSandboxesSandboxProviderIdIndexRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRouteRoute
    }
    '/_authenticated/$orgSlug/sandboxes/new/': {
      id: '/_authenticated/$orgSlug/sandboxes/new/'
      path: '/sandboxes/new'
      fullPath: '/$orgSlug/sandboxes/new/'
      preLoaderRoute: typeof AuthenticatedOrgSlugSandboxesNewIndexRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRouteRoute
    }
    '/_authenticated/_user/settings/account/': {
      id: '/_authenticated/_user/settings/account/'
      path: '/settings/account'
      fullPath: '/settings/account/'
      preLoaderRoute: typeof AuthenticatedUserSettingsAccountIndexRouteImport
      parentRoute: typeof AuthenticatedUserRouteRoute
    }
    '/_authenticated/_user/settings/security/': {
      id: '/_authenticated/_user/settings/security/'
      path: '/settings/security'
      fullPath: '/settings/security/'
      preLoaderRoute: typeof AuthenticatedUserSettingsSecurityIndexRouteImport
      parentRoute: typeof AuthenticatedUserRouteRoute
    }
  }
}

interface AuthenticatedOrgSlugRouteRouteChildren {
  AuthenticatedOrgSlugIndexRoute: typeof AuthenticatedOrgSlugIndexRoute
  AuthenticatedOrgSlugAgentsIndexRoute: typeof AuthenticatedOrgSlugAgentsIndexRoute
  AuthenticatedOrgSlugApiKeysIndexRoute: typeof AuthenticatedOrgSlugApiKeysIndexRoute
  AuthenticatedOrgSlugMembersIndexRoute: typeof AuthenticatedOrgSlugMembersIndexRoute
  AuthenticatedOrgSlugModelsIndexRoute: typeof AuthenticatedOrgSlugModelsIndexRoute
  AuthenticatedOrgSlugSandboxesIndexRoute: typeof AuthenticatedOrgSlugSandboxesIndexRoute
  AuthenticatedOrgSlugSettingsIndexRoute: typeof AuthenticatedOrgSlugSettingsIndexRoute
  AuthenticatedOrgSlugTenantUsersIndexRoute: typeof AuthenticatedOrgSlugTenantUsersIndexRoute
  AuthenticatedOrgSlugTenantsIndexRoute: typeof AuthenticatedOrgSlugTenantsIndexRoute
  AuthenticatedOrgSlugAgentsAgentIdIndexRoute: typeof AuthenticatedOrgSlugAgentsAgentIdIndexRoute
  AuthenticatedOrgSlugAgentsNewIndexRoute: typeof AuthenticatedOrgSlugAgentsNewIndexRoute
  AuthenticatedOrgSlugModelsModelProviderIdIndexRoute: typeof AuthenticatedOrgSlugModelsModelProviderIdIndexRoute
  AuthenticatedOrgSlugModelsNewIndexRoute: typeof AuthenticatedOrgSlugModelsNewIndexRoute
  AuthenticatedOrgSlugSandboxesSandboxProviderIdIndexRoute: typeof AuthenticatedOrgSlugSandboxesSandboxProviderIdIndexRoute
  AuthenticatedOrgSlugSandboxesNewIndexRoute: typeof AuthenticatedOrgSlugSandboxesNewIndexRoute
}

const AuthenticatedOrgSlugRouteRouteChildren: AuthenticatedOrgSlugRouteRouteChildren =
  {
    AuthenticatedOrgSlugIndexRoute: AuthenticatedOrgSlugIndexRoute,
    AuthenticatedOrgSlugAgentsIndexRoute: AuthenticatedOrgSlugAgentsIndexRoute,
    AuthenticatedOrgSlugApiKeysIndexRoute:
      AuthenticatedOrgSlugApiKeysIndexRoute,
    AuthenticatedOrgSlugMembersIndexRoute:
      AuthenticatedOrgSlugMembersIndexRoute,
    AuthenticatedOrgSlugModelsIndexRoute: AuthenticatedOrgSlugModelsIndexRoute,
    AuthenticatedOrgSlugSandboxesIndexRoute:
      AuthenticatedOrgSlugSandboxesIndexRoute,
    AuthenticatedOrgSlugSettingsIndexRoute:
      AuthenticatedOrgSlugSettingsIndexRoute,
    AuthenticatedOrgSlugTenantUsersIndexRoute:
      AuthenticatedOrgSlugTenantUsersIndexRoute,
    AuthenticatedOrgSlugTenantsIndexRoute:
      AuthenticatedOrgSlugTenantsIndexRoute,
    AuthenticatedOrgSlugAgentsAgentIdIndexRoute:
      AuthenticatedOrgSlugAgentsAgentIdIndexRoute,
    AuthenticatedOrgSlugAgentsNewIndexRoute:
      AuthenticatedOrgSlugAgentsNewIndexRoute,
    AuthenticatedOrgSlugModelsModelProviderIdIndexRoute:
      AuthenticatedOrgSlugModelsModelProviderIdIndexRoute,
    AuthenticatedOrgSlugModelsNewIndexRoute:
      AuthenticatedOrgSlugModelsNewIndexRoute,
    AuthenticatedOrgSlugSandboxesSandboxProviderIdIndexRoute:
      AuthenticatedOrgSlugSandboxesSandboxProviderIdIndexRoute,
    AuthenticatedOrgSlugSandboxesNewIndexRoute:
      AuthenticatedOrgSlugSandboxesNewIndexRoute,
  }

const AuthenticatedOrgSlugRouteRouteWithChildren =
  AuthenticatedOrgSlugRouteRoute._addFileChildren(
    AuthenticatedOrgSlugRouteRouteChildren,
  )

interface AuthenticatedUserRouteRouteChildren {
  AuthenticatedUserOnboardingIndexRoute: typeof AuthenticatedUserOnboardingIndexRoute
  AuthenticatedUserOrganizationsIndexRoute: typeof AuthenticatedUserOrganizationsIndexRoute
  AuthenticatedUserSettingsIndexRoute: typeof AuthenticatedUserSettingsIndexRoute
  AuthenticatedUserSettingsAccountIndexRoute: typeof AuthenticatedUserSettingsAccountIndexRoute
  AuthenticatedUserSettingsSecurityIndexRoute: typeof AuthenticatedUserSettingsSecurityIndexRoute
}

const AuthenticatedUserRouteRouteChildren: AuthenticatedUserRouteRouteChildren =
  {
    AuthenticatedUserOnboardingIndexRoute:
      AuthenticatedUserOnboardingIndexRoute,
    AuthenticatedUserOrganizationsIndexRoute:
      AuthenticatedUserOrganizationsIndexRoute,
    AuthenticatedUserSettingsIndexRoute: AuthenticatedUserSettingsIndexRoute,
    AuthenticatedUserSettingsAccountIndexRoute:
      AuthenticatedUserSettingsAccountIndexRoute,
    AuthenticatedUserSettingsSecurityIndexRoute:
      AuthenticatedUserSettingsSecurityIndexRoute,
  }

const AuthenticatedUserRouteRouteWithChildren =
  AuthenticatedUserRouteRoute._addFileChildren(
    AuthenticatedUserRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOrgSlugRouteRoute: typeof AuthenticatedOrgSlugRouteRouteWithChildren
  AuthenticatedUserRouteRoute: typeof AuthenticatedUserRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedChar126SplatRoute: typeof AuthenticatedChar126SplatRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOrgSlugRouteRoute: AuthenticatedOrgSlugRouteRouteWithChildren,
  AuthenticatedUserRouteRoute: AuthenticatedUserRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedChar126SplatRoute: AuthenticatedChar126SplatRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ConfigureRouteRouteChildren {
  ConfigureIndexRoute: typeof ConfigureIndexRoute
}

const ConfigureRouteRouteChildren: ConfigureRouteRouteChildren = {
  ConfigureIndexRoute: ConfigureIndexRoute,
}

const ConfigureRouteRouteWithChildren = ConfigureRouteRoute._addFileChildren(
  ConfigureRouteRouteChildren,
)

interface DocsRouteRouteChildren {
  DocsSitemapDotxmlRoute: typeof DocsSitemapDotxmlRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsSectionIndexRoute: typeof DocsSectionIndexRoute
  DocsApiIndexRoute: typeof DocsApiIndexRoute
  DocsSectionPageIndexRoute: typeof DocsSectionPageIndexRoute
  DocsSectionChar123pageChar125DotmdIndexRoute: typeof DocsSectionChar123pageChar125DotmdIndexRoute
}

const DocsRouteRouteChildren: DocsRouteRouteChildren = {
  DocsSitemapDotxmlRoute: DocsSitemapDotxmlRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsSectionIndexRoute: DocsSectionIndexRoute,
  DocsApiIndexRoute: DocsApiIndexRoute,
  DocsSectionPageIndexRoute: DocsSectionPageIndexRoute,
  DocsSectionChar123pageChar125DotmdIndexRoute:
    DocsSectionChar123pageChar125DotmdIndexRoute,
}

const DocsRouteRouteWithChildren = DocsRouteRoute._addFileChildren(
  DocsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ConfigureRouteRoute: ConfigureRouteRouteWithChildren,
  DocsRouteRoute: DocsRouteRouteWithChildren,
  DocsDotmdRoute: DocsDotmdRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ApiStatusRoute: ApiStatusRoute,
  DevSplatRoute: DevSplatRoute,
  authenticationAuthPathRoute: authenticationAuthPathRoute,
  ApiAstralbeamTokenRoute: ApiAstralbeamTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiChatSplatRoute: ApiChatSplatRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
