export const AUTH_EMAIL_LINK_EXPIRY_SECONDS = 60 * 60
export const AUTH_EMAIL_LINK_EXPIRY_MINUTES = AUTH_EMAIL_LINK_EXPIRY_SECONDS / 60

export const ORGANIZATION_INVITATION_EXPIRY_SECONDS = 48 * 60 * 60
export const ORGANIZATION_INVITATION_EXPIRY_HOURS = ORGANIZATION_INVITATION_EXPIRY_SECONDS /
  (60 * 60)
