// Wraps the Tailwind CLI output into a TypeScript module, because the widget must carry its
// compiled stylesheet as a string to inject into its shadow root (see ARCHITECTURE.md).
const css = await Deno.readTextFile(".generated/styles.css")
const header =
  "// Generated by `deno task generate:styles` from src/styles.css. Do not edit.\n// deno-lint-ignore-file\n"
await Deno.writeTextFile(
  "src/widget/styles.generated.ts",
  `${header}export const widgetStyles: string = ${JSON.stringify(css)}\n`,
)
