// Wraps the Tailwind CLI output into a TypeScript module, because the chat widget must carry its
// compiled stylesheet as a string to inject into its own shadow root.
let css = await Deno.readTextFile(".generated/styles.css")

// Unwrap the @supports gate around Tailwind's default custom properties (`@layer properties`):
// browsers ignore @property inside shadow trees, so the fallback must apply everywhere.
const gate = "@layer properties{@supports "
const gateStart = css.indexOf(gate)
if (gateStart !== -1) {
  const open = css.indexOf("{", gateStart + gate.length)
  let depth = 1
  let close = open + 1
  while (close < css.length && depth > 0) {
    if (css[close] === "{") depth++
    else if (css[close] === "}") depth--
    close++
  }
  // `close - 1` closes the @supports block; the brace after it closes the @layer block.
  const defaults = css.slice(open + 1, close - 1)
  css = css.slice(0, gateStart) + "@layer properties{" + defaults + "}" + css.slice(close + 1)
}
const header =
  "// Generated by `deno task generate:styles` from src/styles.css. Do not edit.\n// deno-lint-ignore-file\n"
await Deno.writeTextFile(
  "src/chat/styles.generated.ts",
  `${header}export const chatStyles: string = ${JSON.stringify(css)}\n`,
)
