/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R404RouteImport } from './routes/404'
import { Route as FaviconDotpngRouteImport } from './routes/favicon[.]png'
import { Route as LicensesDottxtRouteImport } from './routes/licenses[.]txt'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as OgImageDotpngRouteImport } from './routes/og-image[.]png'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SiteDotwebmanifestRouteImport } from './routes/site[.]webmanifest'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SchemasThemeDotschemaDotjsonRouteImport } from './routes/schemas/theme[.]schema[.]json'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const FaviconDotpngRoute = FaviconDotpngRouteImport.update({
  id: '/favicon.png',
  path: '/favicon.png',
  getParentRoute: () => rootRouteImport,
} as any)
const LicensesDottxtRoute = LicensesDottxtRouteImport.update({
  id: '/licenses.txt',
  path: '/licenses.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const OgImageDotpngRoute = OgImageDotpngRouteImport.update({
  id: '/og-image.png',
  path: '/og-image.png',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteDotwebmanifestRoute = SiteDotwebmanifestRouteImport.update({
  id: '/site.webmanifest',
  path: '/site.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemasThemeDotschemaDotjsonRoute =
  SchemasThemeDotschemaDotjsonRouteImport.update({
    id: '/schemas/theme.schema.json',
    path: '/schemas/theme.schema.json',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/favicon.png': typeof FaviconDotpngRoute
  '/licenses.txt': typeof LicensesDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/og-image.png': typeof OgImageDotpngRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/site.webmanifest': typeof SiteDotwebmanifestRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/schemas/theme.schema.json': typeof SchemasThemeDotschemaDotjsonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/favicon.png': typeof FaviconDotpngRoute
  '/licenses.txt': typeof LicensesDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/og-image.png': typeof OgImageDotpngRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/site.webmanifest': typeof SiteDotwebmanifestRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/schemas/theme.schema.json': typeof SchemasThemeDotschemaDotjsonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/favicon.png': typeof FaviconDotpngRoute
  '/licenses.txt': typeof LicensesDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/og-image.png': typeof OgImageDotpngRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/site.webmanifest': typeof SiteDotwebmanifestRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/schemas/theme.schema.json': typeof SchemasThemeDotschemaDotjsonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/favicon.png'
    | '/licenses.txt'
    | '/llms.txt'
    | '/og-image.png'
    | '/privacy'
    | '/robots.txt'
    | '/site.webmanifest'
    | '/sitemap.xml'
    | '/terms'
    | '/schemas/theme.schema.json'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/favicon.png'
    | '/licenses.txt'
    | '/llms.txt'
    | '/og-image.png'
    | '/privacy'
    | '/robots.txt'
    | '/site.webmanifest'
    | '/sitemap.xml'
    | '/terms'
    | '/schemas/theme.schema.json'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/favicon.png'
    | '/licenses.txt'
    | '/llms.txt'
    | '/og-image.png'
    | '/privacy'
    | '/robots.txt'
    | '/site.webmanifest'
    | '/sitemap.xml'
    | '/terms'
    | '/schemas/theme.schema.json'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  FaviconDotpngRoute: typeof FaviconDotpngRoute
  LicensesDottxtRoute: typeof LicensesDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  OgImageDotpngRoute: typeof OgImageDotpngRoute
  PrivacyRoute: typeof PrivacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SiteDotwebmanifestRoute: typeof SiteDotwebmanifestRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  SchemasThemeDotschemaDotjsonRoute: typeof SchemasThemeDotschemaDotjsonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favicon.png': {
      id: '/favicon.png'
      path: '/favicon.png'
      fullPath: '/favicon.png'
      preLoaderRoute: typeof FaviconDotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licenses.txt': {
      id: '/licenses.txt'
      path: '/licenses.txt'
      fullPath: '/licenses.txt'
      preLoaderRoute: typeof LicensesDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og-image.png': {
      id: '/og-image.png'
      path: '/og-image.png'
      fullPath: '/og-image.png'
      preLoaderRoute: typeof OgImageDotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site.webmanifest': {
      id: '/site.webmanifest'
      path: '/site.webmanifest'
      fullPath: '/site.webmanifest'
      preLoaderRoute: typeof SiteDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemas/theme.schema.json': {
      id: '/schemas/theme.schema.json'
      path: '/schemas/theme.schema.json'
      fullPath: '/schemas/theme.schema.json'
      preLoaderRoute: typeof SchemasThemeDotschemaDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  FaviconDotpngRoute: FaviconDotpngRoute,
  LicensesDottxtRoute: LicensesDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  OgImageDotpngRoute: OgImageDotpngRoute,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SiteDotwebmanifestRoute: SiteDotwebmanifestRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  SchemasThemeDotschemaDotjsonRoute: SchemasThemeDotschemaDotjsonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
