// Reports the current project's handwritten, generated, and test lines and its build size.
// Run from `platform`, `sdk`, or `cli`, whose `ready` tasks end with it.
import { execFileSync } from "node:child_process"
import { existsSync, readdirSync, readFileSync, statSync } from "node:fs"
import { basename, join } from "node:path"
import process from "node:process"

// Registry output carries its `Added with:` provenance header, and tools mark their own output.
const generatedHeader =
  /^(?:\/\/|\/?\*+) (?:(?:Previously added|Added) with: |This file was automatically generated|Generated by )/m
const generatedPath = /(?:^|\/)components\/ui\/|(?:^|\/)generated\/|\.gen\.ts$/
const isTest = (path: string) => /\.(?:test|spec)\.[^/]+$/.test(path)

const buildOutputs: Record<string, string> = {
  platform: ".output/astralbeam-platform",
  sdk: "dist",
  cli: "dist",
}

function sizeOf(path: string): number {
  const stat = statSync(path)
  if (!stat.isDirectory()) return stat.size
  return readdirSync(path).reduce((total, entry) => total + sizeOf(join(path, entry)), 0)
}

const files = execFileSync("git", ["ls-files", "--cached", "--others", "--exclude-standard"], {
  encoding: "utf8",
})
  .split("\n")
  .filter((path) => /\.tsx?$/.test(path) && existsSync(path))

const lines = { handwritten: 0, generated: 0, test: 0 }
for (const path of files) {
  const source = readFileSync(path, "utf8")
  const kind =
    generatedPath.test(path) || generatedHeader.test(source.slice(0, 500))
      ? "generated"
      : isTest(path)
        ? "test"
        : "handwritten"
  lines[kind] += source.split("\n").length - 1
}

const output = buildOutputs[basename(process.cwd())]
const megabytes = output && existsSync(output) ? (sizeOf(output) / 1e6).toFixed(1) : undefined
console.log(`Source lines: ${lines.handwritten}`)
console.log(`Generated lines: ${lines.generated}`)
console.log(`Test lines: ${lines.test}`)
console.log(`Build size (${output ?? "none"}): ${megabytes ? `${megabytes} MB` : "not built"}`)
