import { Schema } from "effect"

const ConfigIssueSchema = Schema.Struct({ key: Schema.String, message: Schema.String })

/** Each issue's message is generated by the registry and never repeats the rejected value. */
export class ConfigUpdateInvalid extends Schema.TaggedError<ConfigUpdateInvalid>()(
  "ConfigUpdateInvalid",
  { issues: Schema.Array(ConfigIssueSchema) },
  { httpApiStatus: 422 },
) {
  override readonly message = "Some values could not be saved"
}

export class ConfigValueNotGeneratable extends Schema.TaggedError<ConfigValueNotGeneratable>()(
  "ConfigValueNotGeneratable",
  {},
  { httpApiStatus: 422 },
) {
  override readonly message = "This configuration value cannot be generated"
}

export class ConfigValueNotRevealable extends Schema.TaggedError<ConfigValueNotRevealable>()(
  "ConfigValueNotRevealable",
  {},
  { httpApiStatus: 422 },
) {
  override readonly message = "This configuration value cannot be revealed"
}

/** Loading configuration dies with this, naming the variable but never its value. */
export class ConfigEnvironmentInvalid extends Schema.TaggedError<ConfigEnvironmentInvalid>()(
  "ConfigEnvironmentInvalid",
  { variable: Schema.String },
) {}

/** Carries the migration runner's reason, which names the migration and SQLSTATE for operators. */
export class MigrationsNotApplied extends Schema.TaggedError<MigrationsNotApplied>()(
  "MigrationsNotApplied",
  { message: Schema.String },
  { httpApiStatus: 409 },
) {}
