import { defineConfig } from "orval"

const mutator = (name: string) => ({ path: "src/api/api.ts", name, inferred: true })

export default defineConfig({
  api: {
    input: "../webapp/public/api/openapi.json",
    output: {
      target: "src/api/generated/api.ts",
      // Fetch ignores optionsParamRequired. Require typed auth during generation, not via runtime wrappers.
      // https://orval.dev/docs/reference/configuration/output#client
      client: (clients) => ({
        ...clients.fetch,
        client: async (operation, ...args) => {
          const result = await clients.fetch.client(operation, ...args)
          if (operation.operationId !== "getChatFile") {
            result.implementation = result.implementation
              .replaceAll("params?: ", "params: ")
              .replace("options?: Parameters<", "options: Parameters<")
          }
          return result
        },
      }),
      urlEncodeParameters: true,
      override: {
        header: () => ["Generated by Orval. Do not edit by hand."],
        mutator: mutator("astralBeamApiFetch"),
        fetch: { includeHttpResponseReturnType: false },
        operations: {
          getChatConfig: { mutator: mutator("astralBeamJwtFetch") },
          runChat: { mutator: mutator("astralBeamChatFetch") },
          getChatFile: { mutator: mutator("astralBeamFileFetch") },
        },
      },
    },
  },
})
